#!/usr/bin/env ruby

load 'preload.rb'

gc = ARGV.shift
filename = ARGV.shift
url = ARGV.shift

puts "Getting: #{gc}"
c = Cache.find_or_create(gcid: gc)
puts "Adding #{filename} to #{c}"
c.make_extra_directory
puts %Q[curl -fsS '#{url}' > '#{File.join(c.extra_directory, filename)}']
puts %x[curl -fsS '#{url}' > '#{File.join(c.extra_directory, filename)}']

puts "Export gpx files"
Export.gpx_collections

nil
