#!/usr/local/rvm/rubies/geocaching/bin/ruby

require 'net/http'
require 'dm-core'
require 'dm-migrations'
require 'dm-mysql-adapter'
require 'dm-ar-finders'
require 'dm-types'

settings = YAML.load_file("settings.yaml")
database = settings[:database]
geocaching = settings[:geocaching]
paths = settings[:paths]

DataMapper.setup(:default, database)

DataMapper::Inflector.inflections do |inflect|
	inflect.singular 'caches', 'cache'
end

Dir.glob('./lib/*.rb').each{|f| load "./#{f}"}

DataMapper.auto_upgrade!

HttpInterface.credentials = geocaching
Export.file_root_hash = paths

gc = ARGV.shift
filename = ARGV.shift
url = ARGV.shift

puts "Getting: #{gc}"
c = Cache.find_or_create(gcid: gc)
puts "Adding #{filename} to #{c}"
c.make_extra_directory
puts %Q[curl -fsS '#{url}' > '#{File.join(c.extra_directory, filename)}']
puts %x[curl -fsS '#{url}' > '#{File.join(c.extra_directory, filename)}']

puts "Export gpx files"
Export.gpx_collections

nil
