#!/usr/bin/env ruby

load 'preload.rb'

todo = (0..8).map{|d|
	rd = 1 + d.to_f / 2
	[rd, rd]
}

result = Hash[todo.map{|a, b| ["D#{a}/T#{b}", Cache.all(difficulty: a, terrain: b, found_by_me: false, archived: false).collect(&:to_s)]}]

#result.keys.each{|r|

puts result.to_yaml
