#!/usr/local/rvm/rubies/geocaching/bin/ruby

require 'net/http'
require 'dm-core'
require 'dm-migrations'
require 'dm-mysql-adapter'
require 'dm-ar-finders'
require 'dm-types'

STDOUT.sync = true

settings = YAML.load_file("settings.yaml")
database = settings[:database]
geocaching = settings[:geocaching]
paths = settings[:paths]

DataMapper.setup(:default, database)

DataMapper::Inflector.inflections do |inflect|
	inflect.singular 'caches', 'cache'
end

Dir.glob('./lib/*.rb').each{|f| load "./#{f}"}

DataMapper.auto_upgrade!

HttpInterface.credentials = geocaching
Export.file_root_hash = paths
Cacher.guid = geocaching[:guid]

todo = (0..8).map{|d|
	rd = 1 + d.to_f / 2
	[rd, rd]
}

result = Hash[todo.map{|a, b| ["D#{a}/T#{b}", Cache.all(difficulty: a, terrain: b, found_by_me: false, archived: false).collect(&:to_s)]}]

result.keys.each{|r|

puts result.to_yaml
