#!/usr/bin/env ruby

load 'preload.rb'

m = Cacher.difficulty_matrix
todo = m.select{|k, v| v == 0}.map{|k, v| k}
result = Hash[todo.map{|a, b| ["D#{a}/T#{b}", Cache.all(difficulty: a, terrain: b, found_by_me: false, archived: false).collect(&:to_s)]}]

puts result.to_yaml
