#!/usr/bin/env ruby

load 'preload.rb'

pages = (ENV["PAGES"] || "1").to_i
age = (ENV["AGE"] || "7").to_i
export = ENV["NOEXP"].empty?

ARGV.each{|location|
	puts "Find caches near '#{location}'"
	if location.match(/^GC/)
		c = Cache.find_or_create(gcid: location)
		puts "Using cache #{c}"
		unless c.nil?
			res = Cache.add_all_by_gcid c.find_near(pages)
		end
	else
		l = Location.new(location)
		puts "Using coördinates: #{l}"
		unless l.nil?
			res = Cache.add_all_by_gcid Cache.find_near(l, pages)
		end
	end
	res.each{|c|
		if c.last_update < DateTime.now - age
			puts "Updating: #{c}"
			c.update_from_site! 
			c.update_files
		end
	}
}

if export
	puts "Export gpx files"
	Export.gpx_collections

	puts "Export pdfs and notes (for changed caches)"
	Cache.all(:last_update.gt => DateTime.now - 1).each{|c|
		c.update_files
	}
end

nil
