#!/usr/local/rvm/rubies/geocaching/bin/ruby

require 'net/http'
require 'dm-core'
require 'dm-migrations'
require 'dm-mysql-adapter'
require 'dm-ar-finders'
require 'dm-types'

settings = YAML.load_file("settings.yaml")
database = settings[:database]
geocaching = settings[:geocaching]
paths = settings[:paths]

DataMapper.setup(:default, database)

DataMapper::Inflector.inflections do |inflect|
	inflect.singular 'caches', 'cache'
end

Dir.glob('./lib/*.rb').each{|f| load "./#{f}"}

DataMapper.auto_upgrade!

HttpInterface.credentials = geocaching
Export.file_root_hash = paths

age = (ENV["AGE"] || "0").to_i

ARGV.each{|gc|
	puts "Getting: #{gc}"
	c = Cache.find_or_create(gcid: gc)
	c.update_from_site! if c.last_update < DateTime.now - age
	c.update_files
}

puts "Export gpx files"
Export.gpx_collections

puts "Export pdfs and notes (for changed caches)"
Cache.all(:last_update.gt => DateTime.now - 1).each{|c|
	c.update_files
}

nil
