#!/usr/bin/env ruby

load 'preload.rb'

age = (ENV["AGE"] || "7").to_i

ARGV.each{|gc|
	puts "Getting: #{gc}"
	c = Cache.find_or_create(gcid: gc)
	puts "Making dir for: #{c}"
	puts c.make_extra_directory
}

nil
