#!/usr/bin/env ruby

load 'preload.rb'

puts "Update list of caches found by me (and fetch caches not yet in database)"
Cache.found_by_me

puts "Update caches that I found, but that don't have a found date yet (probably found today)"
to_update = Cache.all(found_by_me: true, found_date: nil).first(50).each{|c|
	c.update_from_site!
	c.update_files
}

puts "Export gpx files"
Export.gpx_collections

puts "Export pdfs and notes (for changed caches)"
Cache.all(:last_update.gt => DateTime.now - 1).each{|c|
	c.update_files
}
nil
