#!/usr/bin/env ruby

load 'preload.rb'

puts "Updating all currently known geocaching lists..."
CacheList.each{|cl|
	puts "Updating: '#{cl}'"
	cl.update_caches_from_site
}

puts "Export gpx files"
Export.gpx_collections

puts "Export pdfs and notes (for changed caches)"
Cache.all(:last_update.gt => DateTime.now - 1).each{|c|
	c.update_files
}

nil
